### ISSUE TITLE
Legg til cron-jobb for cache clean

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMTV_cache#2]
Slett alle fra databasen hvor check-in-tid > 2 min siden
Tabell ukm_tv_caches_caches @ UKMss3

**Comment by mariusmandal** [comment]
OBS: video.ukm.no (som kjører windows) kan ikke kjøre python-heartbeat. Legges til manuelt i tv_caches_caches, med last checkin et par år frem i tid, slik at video.ukm.no alltid er et mulig valg for UKMapi tv.class (cache selector)

**Comment by AsgeirSH** [comment]
Burde vi i tillegg sjekke for om de er deaktivert? Hvis man aktiverer en ny cache før heartbeat kjører på maskinen vil den jo i så fall bli fjernet?

**Comment by AsgeirSH** [comment]
Close, fixed in UKMTVwp
