### ISSUE TITLE
Cache admin

### ISSUE THREAD

**Issue by thusoy** [UKMNorge/UKMTV_cache#6]
Gjør det mulig å administrere cachene fra oversikten, markere hvilke som skal være i bruk, muligens sette forskjellige parametre for utdelingen (en cache skal få 50% av trafikken, mens to andre skal ta 25% hver f. eks).

**Comment by mariusmandal** [comment]
wrong issue referenced
close #5

**Comment by mariusmandal** [comment]
Cachene sier nå i fra hvis de får for mye å gjøre, og gis da en pause. Dermed auto-balanseres lasten på en slik måte at denne funksjonen ikke er nødvendig per dags dato, og forhåpentligvis ikke i fremtiden :)
Ref
https://github.com/mariusmandal/ukm.no/blob/master/salt/wowza/do-heartbeat#L36 @AsgeirSH
